name: Build Python Application with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scapy colorama pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile your_python_file.py

    - name: Upload the built file
      uses: actions/upload-artifact@v3
      with:
        name: built-app
        path: dist/
